### PR TITLE
Update translations.js

### LINKED ISSUE #9: Add translation: Russian
Add Russian translation to the site.

Depends on #7

### PR DESCRIPTION
**Pull request by D-ERF**
in Russian, plurals for minutes and so on are a bit more complicated, I'm sure there is a script developed in this respect, but dunno how to find/use it.
So for now I used short forms to avoid irritating errors.
If it helps: 
if a numeral ends with 0, 5, 6, 7, 8, 9 - it is followed by часов, минут, секунд (also applies to numbers 11, 12, 13, 14)
if a numeral ends with 1 (EXCEPT for 11) - it is followed by час, минута, секунда
if a numeral ends with 2, 3, 4 (EXCEPT for 12, 13, 14) - it is followed by часа, минуты, секунды

### CODE REVIEW

**Comment by D-ERF** [comment]
found an error in my translation, can't edit this pull request, will make another one later

**Comment by D-ERF** [comment]
UPD: 
if a numeral ends with 0, 5, 6, 7, 8, 9 - it is followed by часов, минут, секунд (also applies to numbers 11**, 12, 13, 14**)

**Comment by alvaromontoro** [comment]
@D-ERF You should be able to push changes to your branch and then it will update the pull-request automatically

**Comment by D-ERF** [comment]
Right, branches! Okay, ty, managed somehow) Think now it's ready.

**Comment by D-ERF** [comment]
oops, wrong button...

**Comment by D-ERF** [comment]
Could you merge this already, or do we need to add something else?

**Review by alvaromontoro — APPROVED** [review]

**Comment by alvaromontoro** [comment]
It is not working for me locally because it is missing 'ru' as a valid language in localization.js

**Comment by D-ERF** [comment]
added 'ru' to that file, is there anything else that needs to be done? Sorry, I'm a translator, not a programmer in the slightest sense...

**Review by alvaromontoro — APPROVED** [review]

**Comment by alvaromontoro** [comment]
@D-ERF It looks good now :)
Thanks for your help!

**Pull request merged**
