### PR TITLE
Changed the default color scheme to dark

### PR DESCRIPTION
**Pull request by virejdasani**
When I opened the website, I had to turn my brightness all the way down and so I thought a default dark mode would look a lot better and after implementing it, I think it does!

Screenshot 2021-04-14 at 9 29 27 AM

### CODE REVIEW

**Comment by alvaromontoro** [comment]
The dark mode looks great, but I'd prefer it to be as an option instead of the default. Would it be possible to add a button that toggles between the two?

**Comment by virejdasani** [comment]
Done!
Here is a preview:
Screenshot 2021-04-15 at 11 29 53 AM
Screenshot 2021-04-15 at 11 30 11 AM

**Comment by alvaromontoro** [comment]
This looks amazing!

There's a conflict with script.js. Please check out the latest code and fix the merge conflicts with your branch.

**Comment by virejdasani** [comment]
Done. There is no conflicts anymore.

**Comment by alvaromontoro** [comment]
Thanks for fixing the merge conflicts. I was able to run the code locally and found a couple of bugs:

- As the background is dark, the bubbles with `z-index: -1` don't work as expected (they are behind the dark background). All the z-indexes may need to be upped by 1 to fix this issue.
- In smaller screens, the button to toggle modes is cut and not fully visible (see image below). This happens because it is positioned based on the right side. Instead, it would be better to give it a position from the left (maybe `left:1rem;`?

Screen showing the button clipped at the top left corner

**Comment by virejdasani** [comment]
Done, I fixed both the issues
Screenshot 2021-04-19 at 8 54 47 AM

**Comment by alvaromontoro** [comment]
I still see the button clipped on smaller screens. But the button in the screenshot looks different from the one I get on my screen, it's like I'm missing styles.

**Comment by virejdasani** [comment]
Can you share a screenshot of what it looks like for you

**Comment by alvaromontoro** [comment]
The button still looks like the screenshot above. It doesn't wrap to multiple lines like the one from your screenshot.

**Comment by virejdasani** [comment]
It should be fixed now

**Review by alvaromontoro — APPROVED** [review]

**Comment by alvaromontoro** [comment]
Merged! Thank you, @virejdasani!

**Pull request merged**
